/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene1.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene1.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Desk" position={[-0.065, 0.062, -1.491]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1.112, 1]}>
        <mesh name="Plane001_Plane002_BlackWood001_" geometry={nodes.Plane001_Plane002_BlackWood001_.geometry} material={materials['795548']} />
        <mesh name="Plane001_Plane002_BlackWood001__1" geometry={nodes.Plane001_Plane002_BlackWood001__1.geometry} material={materials['7B4A0A.001']} />
        <mesh name="Plane001_Plane002_BlackWood001__2" geometry={nodes.Plane001_Plane002_BlackWood001__2.geometry} material={materials['1A1A1A']} />
        <mesh name="Plane001_Plane002_BlackWood001__3" geometry={nodes.Plane001_Plane002_BlackWood001__3.geometry} material={nodes.Plane001_Plane002_BlackWood001__3.material} />
        <mesh name="Plane001_Plane002_BlackWood001__4" geometry={nodes.Plane001_Plane002_BlackWood001__4.geometry} material={materials['795548']} />
      </group>
      <group name="SM_ShelfSM_Shelf1" position={[-0.337, 2.041, -1.889]} scale={[1, 1.112, 1]}>
        <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials['455A64']} />
        <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials['795548.001']} />
      </group>
      <group name="keyboard" position={[0.06, 1.153, -1.363]} rotation={[0, -0.165, 0]} scale={[1, 1.112, 1]}>
        <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={materials['mat21.004']} />
        <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={materials['mat22.001']} />
        <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={materials['mat9.002']} />
        <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={materials['mat16.001']} />
      </group>
      <group name="iMac" position={[0.588, 1.087, -1.721]} rotation={[Math.PI, -1.099, Math.PI]} scale={[1, 1.112, 1]}>
        <mesh name="iMac_1" geometry={nodes.iMac_1.geometry} material={materials.Screen} />
        <mesh name="iMac_1_1" geometry={nodes.iMac_1_1.geometry} material={materials.ScreenBlack} />
        <mesh name="iMac_1_2" geometry={nodes.iMac_1_2.geometry} material={materials.iMacBody} />
      </group>
      <mesh name="Comp_Mouse" geometry={nodes.Comp_Mouse.geometry} material={materials['lambert3SG.003']} position={[0.05, 0.055, -0.052]} scale={[1, 1.112, 1]} />
      <group name="plant" position={[-0.771, 1.253, -1.58]} scale={[1, 1.112, 1]}>
        <mesh name="mesh24448074" geometry={nodes.mesh24448074.geometry} material={materials['mat9.003']} />
        <mesh name="mesh24448074_1" geometry={nodes.mesh24448074_1.geometry} material={materials['mat20.001']} />
        <mesh name="mesh24448074_2" geometry={nodes.mesh24448074_2.geometry} material={materials['mat21.005']} />
      </group>
      <group name="Houseplant_7" position={[1.212, -0.075, -1.472]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={materials['Black.001']} />
        <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={materials['Brown.001']} />
        <mesh name="Houseplant_7_3" geometry={nodes.Houseplant_7_3.geometry} material={materials['Plant_Green.001']} />
      </group>
      <group name="Chair" position={[-0.278, 0, -0.708]} rotation={[0, -0.376, 0]} scale={[1, 0.852, 1]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
      </group>
      <group name="group1445929716002" position={[-0.198, 2.164, -1.898]} scale={[1, 1.112, 1]}>
        <mesh name="mesh1445929716002" geometry={nodes.mesh1445929716002.geometry} material={materials['mat21.006']} />
        <mesh name="mesh1445929716002_1" geometry={nodes.mesh1445929716002_1.geometry} material={materials['mat3.002']} />
        <mesh name="mesh1445929716002_2" geometry={nodes.mesh1445929716002_2.geometry} material={materials['mat17.002']} />
        <mesh name="mesh1445929716002_3" geometry={nodes.mesh1445929716002_3.geometry} material={materials['mat8.002']} />
        <mesh name="mesh1445929716002_4" geometry={nodes.mesh1445929716002_4.geometry} material={materials['mat23.004']} />
        <mesh name="mesh1445929716002_5" geometry={nodes.mesh1445929716002_5.geometry} material={materials['7B4A0A.001']} />
        <mesh name="mesh1445929716002_6" geometry={nodes.mesh1445929716002_6.geometry} material={materials['mat20.004']} />
        <mesh name="mesh1445929716002_7" geometry={nodes.mesh1445929716002_7.geometry} material={materials['mat9.005']} />
      </group>
      <group name="Node" position={[-0.84, 2.182, -1.897]} rotation={[1.153, 0.212, 0.156]} scale={[1.007, 1.016, 1.09]}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials['lambert2SG.002']} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials.lambert3SG} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials.lambert7SG} />
        <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={materials.lambert11SG} />
        <mesh name="Node-Mesh002_4" geometry={nodes['Node-Mesh002_4'].geometry} material={materials.lambert10SG} />
        <mesh name="Node-Mesh002_5" geometry={nodes['Node-Mesh002_5'].geometry} material={materials.lambert9SG} />
        <mesh name="Node-Mesh002_6" geometry={nodes['Node-Mesh002_6'].geometry} material={materials.lambert5SG} />
        <mesh name="Node-Mesh002_7" geometry={nodes['Node-Mesh002_7'].geometry} material={materials.lambert8SG} />
        <mesh name="Node-Mesh002_8" geometry={nodes['Node-Mesh002_8'].geometry} material={materials['lambert4SG.001']} />
        <mesh name="Node-Mesh002_9" geometry={nodes['Node-Mesh002_9'].geometry} material={materials.lambert6SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene1.gltf')
